#!/bin/sh

# Builds upstream tarball from the individual upstream distribution
# tarballs.  Called by uscan via debian/watch, or manually:
#   debian/mkorig --upstream-version 110.99.9

set -e

if [ "$1" != "--upstream-version" ] ; then
    echo "Usage: mkorig --upstream-version version"
    exit 1
fi

shift

version=$1
orig=../smlnj-$version

url=https://smlnj.org/dist/working

root_tarballs="ckit config pgraph smlnj-lib MLRISC cml eXene heap2asm \
	       ml-burg ml-lex ml-yacc smlnj-c nlffi ml-lpt \
	       trace-debug-profile doc"
base_tarballs="cm compiler old-basis runtime system"
# bootstrap images for the Debian architectures we build for
archs="amd64 x86 ppc"

mkdir -p $orig
for t in $root_tarballs ; do
    wget -O $orig/$t.tgz $url/$version/$t.tgz
    tar ax -C $orig -f $orig/$t.tgz && rm -f $orig/$t.tgz
done

mkdir -p $orig/bootstrap
for t in $archs ; do
    img=boot.$t-unix.tgz
    wget -O $orig/bootstrap/$img $url/$version/$img
    tar ax -C $orig/bootstrap -f $orig/bootstrap/$img && rm -f $orig/bootstrap/$img
done

mkdir -p $orig/base
for t in $base_tarballs ; do
    wget -O $orig/base/$t.tgz $url/$version/$t.tgz
    tar ax -C $orig/base -f $orig/base/$t.tgz && rm -f $orig/base/$t.tgz
done

rm -f ../smlnj_$version.orig.tar.*
tar --sort=name --owner=0 --group=0 --numeric-owner \
    -C .. -czf ../smlnj_$version.orig.tar.gz smlnj-$version
rm -rf $orig
rm -f ../index.html
