.TH ml-antlr 1 "September 4, 2009"
.SH NAME
ml-antlr \- parser generator for Standard ML
.SH SYNOPSIS
.B ml-antlr
.RI "[--dot] [--latex] file"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ml-antlr
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page. 
The
.B ml-antlr
script is part of the 
.B SML/NJ CM 
(Compilation and Library Manager) that is used to generate standalone
programs.
.TP 
.BI --dot
Generate DOT output (for graphviz).
.TP 
.BI --latex
Generate LaTeX output.
.SH SEE ALSO
.BR sml (1),
.BR ml-lex (1),
.BR ml-ulex (1),
.BR ml-yacc (1).
.br
The programs are documented fully by
.IR "SML/NJ Language Processing Tools: User Guide" ,
Aaron Turon and John Reppy, which is
available in
.IR /usr/share/doc/smlnj-doc/ml-lpt_manual.pdf.gz .
.SH AUTHOR
This manual page was written by Daniel Moerner <dmoerner@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
