.TH ml-lex 1 "October 25, 2002"
.SH NAME
ml-lex \- a parser generator for ML
.SH SYNOPSIS
.B ml-lex 
.I file.lex
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ml-lex
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page. 
The
.B ml-lex
proogram generates a lexical analyzer from the specification in
.IR file.lex ", and produces the file, " file.lex.sml "."
.SH SEE ALSO
.BR sml (1),
.BR ml-yacc (1),
.BR ml-makedepend (1),
.BR ml-build (1).
.br
The programs are documented fully by
.IR "A lexical analyzer generator for Standard ML" ,
Andrew W. Appel, James S. Mattson, and David R. Tarditi
which is available via 
<http://www.cs.princeton.edu/~appel/modern/ml/ml-lex/manual.html>.
.SH AUTHOR
This manual page was written by Aaron Matthew Read <amread@nyx.net>,
for the Debian GNU/Linux system (but may be used by others)
