.TH ml-makedepend 1 "October 25, 2002"
.SH NAME
ml-makedepend \- list files a ML program depends upon
.SH SYNOPSIS
.B ml-makedepend 
.RI "[ " DU-options " ] "
.RB "[ " -n " ] [ " -f 
.IB makefile " ] " " project.cm target"
.br
.B ml-makedepend
.RI "[ " DU-options " ] "
.RB "[ " -a 
.IR arch " ] [ "
.BI -o " os"
.RB " ] [ " -f 
.IR makefile " ] " "project.cm target"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ml-makedepend
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page. 
The
.B ml-makedepend
script is part of the 
.B SML/NJ CM 
(Compilation and Library Manager) that is used to generate
a list of files that a ML program depends on for use by
.BR make .
.SH OPTIONS
A summary of options is included below.
.TP
.B -n
.BR ml-makedepend " usually uses the " make 
.RI variables " $(ARCH) " and " $(OPSYS) " 
in the filenames for the
.IR Makefile ". "
This option disables this feature.
.TP
.BI -a " arch"
.RI "Use " arch " in place of " $(ARCH) .
.TP
.BI -o " os"
.RI "Use " os " in place of " $(OPSYS) .
.TP
.BI -f " makefile"
Name of the 
.I makefile
to be used rather than the default
.IR Makefile .
.TP
.BI -D name = value
Set CM variable to given value.
.TP
.BI -D name
Set CM variable to 1.
.TP
.BI -U name
Unset CM variable.
.SH SEE ALSO
.BR sml (1),
.BR ml-lex (1),
.BR ml-build (1),
.BR ml-yacc (1).
.br
The programs are documented fully by
.IR "CM: The SML/NJ Compilation and Library Manager, User Manual" , 
Matthias Blume, which is
available via <http://cm.bell-labs.com/cm/cs/what/smlnj/doc/CM/new.pdf>.
.SH AUTHOR
This manual page was written by Aaron Matthew Read <amread@nyx.net>,
for the Debian GNU/Linux system (but may be used by others).
