.TH ml-ulex 1 "September 4, 2009"
.SH NAME
ml-ulex \- lexer generator for Standard ML
.SH SYNOPSIS
.B ml-ulex
.RI "[--dot] [--dump] [--match] [--ml-lex-mode] [--minimize] file"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ml-ulex
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page. 
The
.B ml-ulex
script is part of the 
.B SML/NJ CM 
(Compilation and Library Manager) that is used to generate standalone
programs.
.SH OPTIONS
A summary of some of the options is included below.
.TP 
.BI --dot
Generate DOT output (for graphviz).
.TP 
.BI --match
Enter interactive matching mode.
.TP 
.BI --ml-lex-mode
Operate in ml-lex compatability mode.
.SH SEE ALSO
.BR sml (1),
.BR ml-antlr (1),
.BR ml-lex (1),
.BR ml-yacc (1).
.br
The programs are documented fully by
.IR "CM: The SML/NJ Compilation and Library Manager, User Manual" , 
Matthias Blume, which is
available via <http://cm.bell-labs.com/cm/cs/what/smlnj/doc/CM/new.pdf>.
.SH AUTHOR
This manual page was written by Daniel Moerner <dmoerner@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
