.TH ml-yacc 1 "October 25, 2002"
.SH NAME
ml-yacc \- a parser generator for ML
.SH SYNOPSIS
.B ml-yacc 
.I file
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ml-yacc
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page. 
The
.B ml-yacc
program generates a parser for an LALR language from the specification in
.IR file ". Two files are generated, " file.sig " and " file.sml .
.SH SEE ALSO
.BR sml (1),
.BR ml-lex (1),
.BR ml-makedepend (1),
.BR ml-build (1).
.br
The programs are documented fully by
.IR "The ML-Yacc User's Manual" ", David R. Tarditi and Andrew W. Appel, "
which is
available in
.IR /usr/share/doc/smlnj-doc/mlyacc.pdf.gz .
.SH AUTHOR
This manual page was written by Aaron Matthew Read <amread@nyx.net>,
for the Debian GNU/Linux system (but may be used by others)
