#!/bin/sh

set -e

if [ $# -ne 2 ] ; then
    echo "usage: register name target"
    exit 1
fi

name=$1
target=$2

/usr/lib/smlnj/bin/deregister $name

echo "$name $target" >> /usr/lib/smlnj/lib/pathconfig
